#!/bin/zsh

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

# file: Scripts/minibox-prepare-macos
# author: Kaito Udagawa <umireon@kaito.tokyo>
# version: 0.1.0
# date: 2026-04-28

setopt errexit nounset nullglob pipefail warn_create_global

MINIBOX_VERSION="0.1.0"
: "${MINIBOX_DATA_DIR:=$HOME/Library/Application Support/tokyo.kaito.MiniboxSwift.minibox}"
export MINIBOX_DATA_DIR

usage() {
	printf 'Usage: minibox-prepare-macos --base-image-name=NAME\n'
	printf '  --base-image-name=NAME  Name of the base image to prepare. Mandatory.\n'
	printf '  --force                 Force to overwrite existing files.\n'
	printf '  --sudo=sudo             Command to use for sudo operations. Optional.\n'
	printf '  --skip-steps=S1,S2      Comma-separated list of step names to skip. Optional.\n'
	printf '  --step=NAME	          Step name to execute. Internal use only.\n'
}

typeset -A opts
typeset -a posArgs
while (($#)); do
	if [[ $1 == -- ]]; then
		posArgs+=("${@:2}")
		set --
		break
	elif [[ $1 == --?*=* ]]; then
		opts[${1%%=*}]="${1#*=}"
	elif [[ $1 == --?* ]]; then
		if [[ -z ${2+set} || $2 == --* ]]; then
			opts[$1]=''
		else
			opts[$1]="${2}"
			shift
		fi
	else
		posArgs+=("$1")
	fi
	shift
done

getoption() {
	case ${2-optional} in
	optional)
		printf '%s' "${opts[$1]-}"
		;;
	required)
		if ((${+opts[$1]})); then
			printf '%s' "${opts[$1]}"
		else
			printf 'ERROR: %s is required.\n' "$1" >&2
			usage >&2
			exit 64
		fi
		;;
	flag)
		printf '%s' "${+opts[$1]}"
		;;
	esac
}

if (($(getoption --version flag))); then
	printf 'miniboxPrepareMacOSVersion=%s\n' "${MINIBOX_VERSION}"
	exit 0
fi

if (($(getoption --help flag))); then
	usage >&2
	exit 0
fi


baseImageName=$(getoption --base-image-name required)
force=$(getoption --force flag)
sudo=${$(getoption --sudo):-sudo}
skipSteps=("${(s:,:)$(getoption --skip-steps)}")
step=${$(getoption --step):-all}

srcBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}.miniboxvm"
destBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}_github.miniboxvm"
volumePath="${MINIBOX_DATA_DIR}/Volumes/${baseImageName}_github"
scriptPath="$0"

minibox-prepare-macos-all() {
	trap "diskutil eject \"${volumePath}/Data\" >/dev/null 2>&1 || true" INT TERM EXIT
	minibox-prepare-macos-clone "${(kv)opts[@]}"
	minibox-prepare-macos-mount "${(kv)opts[@]}"
	"${sudo}" "${scriptPath}" "${(kv)opts[@]}" --step=sudomodify
	minibox-prepare-macos-eject
	minibox-prepare-macos-manualsetup "${(kv)opts[@]}"
}

minibox-prepare-macos-clone() {
	if [[ -d "${destBaseImagePath}" ]]; then
		if ((${force})); then
			printf '#==> Removing existing base image: %s\n' "${destBaseImagePath}"
			rm -rf "${destBaseImagePath}"
		else
			printf 'ERROR: Base image already exists: %s\n' "${destBaseImagePath}" >&2
			printf 'ERROR: Try again with --force to overwrite.\n' >&2
			exit 1
		fi
	fi

	printf '#==> Cloning base image: %s\n' "${srcBaseImagePath}"
	cp -cR "${srcBaseImagePath}" "${destBaseImagePath}"
}

minibox-prepare-macos-mount() {
	local attachPlist devEntry mountPoint
	mountPoint="${volumePath}/Data"
	mkdir -p "${mountPoint}"

	printf '#==> Mounting Disk.asif: %s\n' "${mountPoint}"
	devEntry=$(
		diskutil image attach --plist --noMount "${destBaseImagePath}/Disk.asif" |
			plutil -convert json -o - - |
			jq -r '.["system-entities"][] | select(.role == "Data") | .["dev-entry"]'
	)
	diskutil umount "${volumePath}/Data" >/dev/null 2>&1 || true
	diskutil mount -mountOptions owners -mountPoint "${mountPoint}" "/dev/${devEntry}"
}

minibox-prepare-macos-sudomodify() {
	cd "${volumePath}/Data"

	cat <<'EOF' >Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-init.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>tokyo.kaito.MiniboxSwift.minibox-init</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/dash</string>
		<string>/usr/local/libexec/minibox-init.sh</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<false/>
</dict>
</plist>
EOF
	chmod 644 Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-init.plist

	cat <<'EOF' >Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-console.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>tokyo.kaito.MiniboxSwift.minibox-console</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/libexec/getty</string>
		<string>std.9600</string>
		<string>tty.virtio</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<false/>
</dict>
</plist>
EOF
	chmod 644 Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-console.plist

	mkdir -p usr/local/libexec
	cat <<'EOF' >usr/local/libexec/minibox-init.sh
sysadminctl -addUser runner -password runner -admin
sysadminctl -autologin set -userName runner -password runner
EOF
	chmod 755 usr/local/libexec/minibox-init.sh
}

minibox-prepare-macos-eject() {
	diskutil eject "${volumePath}/Data" || true
}

minibox-prepare-macos-manualsetup() {
	printf '#==> Starting manual setup...\n'
	minibox-view --bundle-path "${destBaseImagePath}"
}

"minibox-prepare-macos-${step}" "${(kv)opts[@]}" -- "${posArgs[@]}"
