#!/bin/zsh

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

setopt errexit nounset nullglob pipefail warn_create_global

: "${MINIBOX_DATA_DIR:=$HOME/Library/Application Support/tokyo.kaito.MiniboxSwift.minibox}"
export MINIBOX_DATA_DIR

usage() {
	printf 'Usage: minibox-prepare --base-image-name=NAME --variant=NAME\n'
	printf '  --baseImageName=NAME  Name of the base image to prepare. Mandatory.\n'
	printf '  --variant=NAME          Variant name for preparation process. Mandatory.\n'
	printf '  --no-sudo               Do not use sudo for operations. Optional.\n'
	printf '  --force                 Force to overwrite existing files.\n'
	printf '  --skip-steps=S1,S2      Comma-separated list of step names to skip. Optional.\n'
	printf '  --step=NAME	          Step name to execute. Internal use only.\n'
}

typeset -A opts
typeset -a posArgs
while (($#)); do
	if [[ $1 == -- ]]; then
		posArgs+=("${@:2}")
		set --
		break
	elif [[ $1 == --?*=* ]]; then
		opts[${1%%=*}]="${1#*=}"
	elif [[ $1 == --?* ]]; then
		if [[ ${2:---} == --* ]]; then
			opts[$1]=''
		else
			opts[$1]="$2"
			shift
		fi
	else
		posArgs+=("$1")
	fi
	shift
done

getoption() {
	if ((${+opts[$1]})); then
		printf '%s' "${opts[$1]}"
	elif [[ ${2:-} == required ]]; then
		printf 'ERROR: %s is required.\n' "$1" >&2
		usage >&2
		exit 64
	fi
}

variant=$(getoption --variant required)

prepare_command="minibox-prepare-${variant}"

if ! whence "${prepare_command}" >/dev/null 2>&1; then
	printf 'ERROR: Unsupported variant: %s\n' "${variant}" >&2
	printf 'ERROR: Command %s not found.\n' "${prepare_command}" >&2
	usage >&2
	exit 127
fi

"${prepare_command}" "${(kv)opts[@]}"
