#!/bin/zsh

# SPDX-FileCopyrightText: 2026 Kaito Udagawa <umireon@kaito.tokyo>
#
# SPDX-License-Identifier: Apache-2.0

setopt errexit nounset nullglob pipefail warn_create_global

: "${MINIBOX_DATA_DIR:=$HOME/Library/Application Support/tokyo.kaito.MiniboxSwift.minibox}"
export MINIBOX_DATA_DIR

usage() {
	printf 'Usage: minibox-prepare-github --base-image-name=NAME\n'
	printf '  --base-image-name=NAME  Name of the base image to prepare. Mandatory.\n'
	printf '  --no-sudo               Do not use sudo for operations. Optional.\n'
	printf '  --force                 Force to overwrite existing files.\n'
	printf '  --skip-steps=S1,S2      Comma-separated list of step names to skip. Optional.\n'
	printf '  --step=NAME	          Step name to execute. Internal use only.\n'
}

typeset -A opts
typeset -a posArgs
while (($#)); do
	if [[ $1 == -- ]]; then
		posArgs+=("${@:2}")
		set --
		break
	elif [[ $1 == --?*=* ]]; then
		opts[${1%%=*}]="${1#*=}"
	elif [[ $1 == --?* ]]; then
		if [[ ${2:---} == --* ]]; then
			opts[$1]=''
		else
			opts[$1]="$2"
			shift
		fi
	else
		posArgs+=("$1")
	fi
	shift
done

getoption() {
	if ((${+opts[$1]})); then
		printf '%s' "${opts[$1]}"
	elif [[ ${2:-} == required ]]; then
		printf 'ERROR: %s is required.\n' "$1" >&2
		usage >&2
		exit 64
	fi
}

baseImageName=$(getoption --base-image-name required)
noSudo=$(getoption --no-sudo)
skipSteps=$(getoption --skip-steps)

srcBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}.miniboxvm"
destBaseImagePath="${MINIBOX_DATA_DIR}/BaseImages/${baseImageName}_github.miniboxvm"
volumePath="${MINIBOX_DATA_DIR}/Volumes/${baseImageName}_github"
scriptPath="$0"
if ((${+noSudo})); then
	sudo=:
else
	sudo=sudo
fi

minibox-prepare-github-all() {
	trap "diskutil eject \"${volumePath}/Data\" >/dev/null 2>&1 || true" INT TERM EXIT
	minibox-prepare-github-clone "${(kv)opts[@]}"
	minibox-prepare-github-mount "${(kv)opts[@]}"
	"${sudo}" "${scriptPath}" "${(kv)opts[@]}" --step=sudomodify
	minibox-prepare-github-eject
	minibox-prepare-github-manualsetup "${(kv)opts[@]}"
}

minibox-prepare-github-clone() {
	if [[ -d "${destBaseImagePath}" ]]; then
		if ((${+opts[--force]})); then
			printf '#==> Removing existing base image: %s\n' "${destBaseImagePath}"
			rm -rf "${destBaseImagePath}"
		else
			printf 'ERROR: Base image already exists: %s\n' "${destBaseImagePath}" >&2
			printf 'ERROR: Try again with --force to overwrite.\n' >&2
			exit 1
		fi
	fi

	printf '#==> Cloning base image: %s\n' "${srcBaseImagePath}"
	cp -cR "${srcBaseImagePath}" "${destBaseImagePath}"
}

minibox-prepare-github-mount() {
	local attachPlist devEntry mountPoint
	mountPoint="${volumePath}/Data"
	mkdir -p "${mountPoint}"

	printf '#==> Mounting Disk.asif: %s\n' "${mountPoint}"
	devEntry=$(
		diskutil image attach --plist --noMount "${destBaseImagePath}/Disk.asif" |
			plutil -convert json -o - - |
			jq -r '.["system-entities"][] | select(.role == "Data") | .["dev-entry"]'
	)
	diskutil umount "${volumePath}/Data" >/dev/null 2>&1 || true
	diskutil mount -mountOptions owners -mountPoint "${mountPoint}" "/dev/${devEntry}"
}

minibox-prepare-github-sudomodify() {
	cd "${volumePath}/Data"

	cat <<'EOF' >Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-init.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>tokyo.kaito.MiniboxSwift.minibox-init</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/dash</string>
		<string>/usr/local/libexec/minibox-init.sh</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<false/>
</dict>
</plist>
EOF
	chmod 644 Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-init.plist

	cat <<'EOF' >Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-console.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>tokyo.kaito.MiniboxSwift.minibox-console</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/libexec/getty</string>
		<string>std.9600</string>
		<string>tty.virtio</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>KeepAlive</key>
	<false/>
</dict>
</plist>
EOF
	chmod 644 Library/LaunchDaemons/tokyo.kaito.MiniboxSwift.minibox-console.plist

	mkdir -p usr/local/libexec
	cat <<'EOF' >usr/local/libexec/minibox-init.sh
sysadminctl -addUser runner -password runner -admin
sysadminctl -autologin set -userName runner -password runner
EOF
	chmod 755 usr/local/libexec/minibox-init.sh
}

minibox-prepare-github-eject() {
	diskutil eject "${volumePath}/Data" || true
}

minibox-prepare-github-manualsetup() {
	printf '#==> Starting manual setup...\n'
	minibox-view --bundle-path "${destBaseImagePath}"
}

"minibox-prepare-github-${opts[--step]-all}" "${(kv)opts[@]}"
